<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyMediaImport.Core\MyMediaImport.Core.csproj" />
    <ProjectReference Include="..\MyMediaImport.Windows\MyMediaImport.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ApplicationIcon>Assets\MyMediaImport.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\MyMediaImport.ico" />
  </ItemGroup>

</Project>
