using System.Collections.ObjectModel;
using System.Globalization;
using System.Text;

namespace MyMediaImport.Core;

public sealed class PathTemplate
{
    private const string CaptureName = "capture";
    private const string CaptureUtcName = "captureUtc";
    private const string CaptureOffsetName = "captureOffset";
    private const string OriginalName = "original";
    private const string ExtensionName = "ext";
    private const string CollisionName = "collision";

    public static IReadOnlyList<PathTemplatePlaceholder> SupportedPlaceholders { get; } =
        new ReadOnlyCollection<PathTemplatePlaceholder>(
        [
            new($"{{{CaptureName}:FORMAT}}", "Local capture time.", $"{{{CaptureName}:yyyy-MM-dd_HHmmss}}"),
            new($"{{{CaptureUtcName}:FORMAT}}", "Capture time converted to UTC.", $"{{{CaptureUtcName}:yyyy-MM-dd_HHmmss'Z'}}"),
            new($"{{{CaptureOffsetName}}}", "Resolved UTC offset without a colon.", $"{{{CaptureOffsetName}}}"),
            new($"{{{OriginalName}}}", "Original filename without extension.", null),
            new($"{{{ExtensionName}}}", "Normalized lowercase extension without leading dot.", null),
            new($"{{{CollisionName}:FORMAT}}", "Empty for the first filename, then suffixes such as _02, _03.", $"{{{CollisionName}:_00}}")
        ]);

    public PathTemplate(string template)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(template);
        Template = template;
    }

    public string Template { get; }

    public string Render(MediaItem mediaItem, int collisionNumber = 1)
    {
        ArgumentNullException.ThrowIfNull(mediaItem);
        ArgumentOutOfRangeException.ThrowIfLessThan(collisionNumber, 1);

        StringBuilder result = new(Template.Length);

        for (int index = 0; index < Template.Length; index++)
        {
            char character = Template[index];
            if (character == '}')
            {
                throw new FormatException("The path template contains an unmatched closing brace.");
            }

            if (character != '{')
            {
                result.Append(character);
                continue;
            }

            int end = Template.IndexOf('}', index + 1);
            if (end < 0)
            {
                throw new FormatException("The path template contains an unmatched opening brace.");
            }

            string placeholder = Template[(index + 1)..end];
            result.Append(RenderPlaceholder(placeholder, mediaItem, collisionNumber));
            index = end;
        }

        return Environment.ExpandEnvironmentVariables(result.ToString());
    }

    private static string RenderPlaceholder(
        string placeholder,
        MediaItem mediaItem,
        int collisionNumber)
    {
        if (placeholder == OriginalName)
        {
            return Path.GetFileNameWithoutExtension(mediaItem.Name);
        }

        if (placeholder == ExtensionName)
        {
            return Path.GetExtension(mediaItem.Name)
                .TrimStart('.')
                .ToLowerInvariant();
        }

        if (placeholder == CaptureOffsetName)
        {
            TimeSpan offset = RequireResolvedCaptureTime(mediaItem).Offset;
            char sign = offset < TimeSpan.Zero ? '-' : '+';
            TimeSpan absoluteOffset = offset.Duration();
            return $"{sign}{(int)absoluteOffset.TotalHours:00}{absoluteOffset.Minutes:00}";
        }

        if (placeholder.StartsWith($"{CaptureUtcName}:", StringComparison.Ordinal))
        {
            string format = RequireFormat(placeholder, $"{CaptureUtcName}:");
            return RequireResolvedCaptureTime(mediaItem)
                .ToUniversalTime()
                .ToString(format, CultureInfo.InvariantCulture);
        }

        if (placeholder.StartsWith($"{CaptureName}:", StringComparison.Ordinal))
        {
            string format = RequireFormat(placeholder, $"{CaptureName}:");
            string value = RequireCaptureTime(mediaItem)
                .LocalTime
                .ToString(format, CultureInfo.InvariantCulture);

            if (value.Contains('Z'))
            {
                throw new FormatException(
                    "A literal Z may only be generated by a captureUtc placeholder.");
            }

            return value;
        }

        if (placeholder.StartsWith($"{CollisionName}:", StringComparison.Ordinal))
        {
            string format = RequireFormat(placeholder, $"{CollisionName}:");
            return collisionNumber == 1
                ? string.Empty
                : collisionNumber.ToString(format, CultureInfo.InvariantCulture);
        }

        throw new FormatException($"Unknown path template placeholder '{{{placeholder}}}'.");
    }

    private static string RequireFormat(string placeholder, string prefix)
    {
        string format = placeholder[prefix.Length..];
        return format.Length > 0
            ? format
            : throw new FormatException($"Placeholder '{{{placeholder}}}' requires a format.");
    }

    private static CaptureTimestamp RequireCaptureTime(MediaItem mediaItem) =>
        mediaItem.CaptureTime
        ?? throw new MissingCaptureTimeException(
            $"Media item '{mediaItem.Id}' has no capture time.");

    private static DateTimeOffset RequireResolvedCaptureTime(MediaItem mediaItem) =>
        RequireCaptureTime(mediaItem).ResolvedTime
        ?? throw new UnresolvedCaptureTimeException(
            $"Media item '{mediaItem.Id}' has a capture time with an unknown UTC offset. " +
            "Resolve its capture timezone before using captureUtc.");
}

public sealed record PathTemplatePlaceholder(string Syntax, string Description, string? Example);
